name: liberacion continua 

on:
    release:
        types: created

#para subir archivos al repositorio debe tener permiso de escritura
permissions:
    contents: write
jobs:
    compilar-y-liberar:
        runs-on: ubuntu-latest
        steps: 
            - name: Clonar el repositorio
              uses: actions/checkout@v4
            - name: Compilar codigo
              run: gcc hola.c -o hola -O3
            - name: subir el ejecutable
              uses: svenstaro/upload-release-action@v2
              with:
                file: hola
                repo_token: ${{ secrets.GITHUB_TOKEN }}


