name: integración continua 

#cuando se debe de ejecutar
on: push

#lista de scripts para que se ejecuten
jobs:
    compilar-y-ejecutar:
        runs-on: ubuntu-latest
        steps: 
            - name: Clonar el repositorio
              uses: actions/checkout@v4
            - name: Compilar codigo
              run: gcc hola.c -o hola
            - name: Ejecuta el codigo
              run: ./hola